
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class Background : Luban.BeanBase
{
    public Background(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["spritePath"].IsString) { throw new SerializationException(); }  SpritePath = _buf["spritePath"]; }
        { if(!_buf["scrollSpeed"].IsNumber) { throw new SerializationException(); }  ScrollSpeed = _buf["scrollSpeed"]; }
    }

    public static Background DeserializeBackground(JSONNode _buf)
    {
        return new leiting.Background(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 背景ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 背景图片路径
    /// </summary>
    public readonly string SpritePath;
    /// <summary>
    /// 滚动速度
    /// </summary>
    public readonly float ScrollSpeed;
   
    public const int __ID__ = 504395838;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "spritePath:" + SpritePath + ","
        + "scrollSpeed:" + ScrollSpeed + ","
        + "}";
    }
}
}

