
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class BossSkill : Luban.BeanBase
{
    public BossSkill(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["bossId"].IsString) { throw new SerializationException(); }  BossId = _buf["bossId"]; }
        { if(!_buf["bulletId"].IsString) { throw new SerializationException(); }  BulletId = _buf["bulletId"]; }
        { if(!_buf["triggerHpPercent"].IsNumber) { throw new SerializationException(); }  TriggerHpPercent = _buf["triggerHpPercent"]; }
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
        { if(!_buf["bulletCount"].IsNumber) { throw new SerializationException(); }  BulletCount = _buf["bulletCount"]; }
        { if(!_buf["spreadAngle"].IsNumber) { throw new SerializationException(); }  SpreadAngle = _buf["spreadAngle"]; }
    }

    public static BossSkill DeserializeBossSkill(JSONNode _buf)
    {
        return new leiting.BossSkill(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// Boss技能ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属Boss ID
    /// </summary>
    public readonly string BossId;
    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly string BulletId;
    /// <summary>
    /// 触发血量百分比
    /// </summary>
    public readonly float TriggerHpPercent;
    /// <summary>
    /// 冷却
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int BulletCount;
    /// <summary>
    /// 散布角
    /// </summary>
    public readonly float SpreadAngle;
   
    public const int __ID__ = -105777708;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "bossId:" + BossId + ","
        + "bulletId:" + BulletId + ","
        + "triggerHpPercent:" + TriggerHpPercent + ","
        + "cooldown:" + Cooldown + ","
        + "bulletCount:" + BulletCount + ","
        + "spreadAngle:" + SpreadAngle + ","
        + "}";
    }
}
}

