
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class BossPhasePattern : Luban.BeanBase
{
    public BossPhasePattern(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["bossPhaseId"].IsString) { throw new SerializationException(); }  BossPhaseId = _buf["bossPhaseId"]; }
        { if(!_buf["sort"].IsNumber) { throw new SerializationException(); }  Sort = _buf["sort"]; }
        { if(!_buf["patternId"].IsString) { throw new SerializationException(); }  PatternId = _buf["patternId"]; }
    }

    public static BossPhasePattern DeserializeBossPhasePattern(JSONNode _buf)
    {
        return new leiting.BossPhasePattern(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 阶段弹幕行ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属Boss阶段ID
    /// </summary>
    public readonly string BossPhaseId;
    /// <summary>
    /// 循环顺序
    /// </summary>
    public readonly int Sort;
    /// <summary>
    /// 子弹或导弹发射模式ID
    /// </summary>
    public readonly string PatternId;
   
    public const int __ID__ = 1716737202;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "bossPhaseId:" + BossPhaseId + ","
        + "sort:" + Sort + ","
        + "patternId:" + PatternId + ","
        + "}";
    }
}
}

