
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class BossPhase : Luban.BeanBase
{
    public BossPhase(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["bossId"].IsString) { throw new SerializationException(); }  BossId = _buf["bossId"]; }
        { if(!_buf["displayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["displayName"]; }
        { if(!_buf["triggerHpPercent"].IsNumber) { throw new SerializationException(); }  TriggerHpPercent = _buf["triggerHpPercent"]; }
        { if(!_buf["attackInterval"].IsNumber) { throw new SerializationException(); }  AttackInterval = _buf["attackInterval"]; }
        { if(!_buf["burstCount"].IsNumber) { throw new SerializationException(); }  BurstCount = _buf["burstCount"]; }
        { if(!_buf["burstInterval"].IsNumber) { throw new SerializationException(); }  BurstInterval = _buf["burstInterval"]; }
        { if(!_buf["movementRangeX"].IsNumber) { throw new SerializationException(); }  MovementRangeX = _buf["movementRangeX"]; }
        { if(!_buf["movementRangeY"].IsNumber) { throw new SerializationException(); }  MovementRangeY = _buf["movementRangeY"]; }
        { if(!_buf["movementSpeed"].IsNumber) { throw new SerializationException(); }  MovementSpeed = _buf["movementSpeed"]; }
    }

    public static BossPhase DeserializeBossPhase(JSONNode _buf)
    {
        return new leiting.BossPhase(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// Boss阶段ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属Boss ID
    /// </summary>
    public readonly string BossId;
    /// <summary>
    /// 阶段显示名
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 触发血量百分比
    /// </summary>
    public readonly float TriggerHpPercent;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// 每次连发轮数
    /// </summary>
    public readonly int BurstCount;
    /// <summary>
    /// 连发间隔
    /// </summary>
    public readonly float BurstInterval;
    /// <summary>
    /// 移动范围X
    /// </summary>
    public readonly float MovementRangeX;
    /// <summary>
    /// 移动范围Y
    /// </summary>
    public readonly float MovementRangeY;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MovementSpeed;
   
    public const int __ID__ = -108645122;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "bossId:" + BossId + ","
        + "displayName:" + DisplayName + ","
        + "triggerHpPercent:" + TriggerHpPercent + ","
        + "attackInterval:" + AttackInterval + ","
        + "burstCount:" + BurstCount + ","
        + "burstInterval:" + BurstInterval + ","
        + "movementRangeX:" + MovementRangeX + ","
        + "movementRangeY:" + MovementRangeY + ","
        + "movementSpeed:" + MovementSpeed + ","
        + "}";
    }
}
}

