
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class BulletPattern : Luban.BeanBase
{
    public BulletPattern(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["patternType"].IsString) { throw new SerializationException(); }  PatternType = _buf["patternType"]; }
        { if(!_buf["bulletId"].IsString) { throw new SerializationException(); }  BulletId = _buf["bulletId"]; }
        { if(!_buf["firePointGroup"].IsString) { throw new SerializationException(); }  FirePointGroup = _buf["firePointGroup"]; }
        { if(!_buf["firePointOffsetX"].IsNumber) { throw new SerializationException(); }  FirePointOffsetX = _buf["firePointOffsetX"]; }
        { if(!_buf["firePointOffsetY"].IsNumber) { throw new SerializationException(); }  FirePointOffsetY = _buf["firePointOffsetY"]; }
        { if(!_buf["baseAngle"].IsNumber) { throw new SerializationException(); }  BaseAngle = _buf["baseAngle"]; }
        { if(!_buf["bulletCount"].IsNumber) { throw new SerializationException(); }  BulletCount = _buf["bulletCount"]; }
        { if(!_buf["angleStep"].IsNumber) { throw new SerializationException(); }  AngleStep = _buf["angleStep"]; }
        { if(!_buf["spreadAngle"].IsNumber) { throw new SerializationException(); }  SpreadAngle = _buf["spreadAngle"]; }
        { if(!_buf["bulletSpeed"].IsNumber) { throw new SerializationException(); }  BulletSpeed = _buf["bulletSpeed"]; }
        { if(!_buf["bulletLifetime"].IsNumber) { throw new SerializationException(); }  BulletLifetime = _buf["bulletLifetime"]; }
        { if(!_buf["rotate"].IsBoolean) { throw new SerializationException(); }  Rotate = _buf["rotate"]; }
        { if(!_buf["rotationSpeed"].IsNumber) { throw new SerializationException(); }  RotationSpeed = _buf["rotationSpeed"]; }
        { if(!_buf["aimAtPlayer"].IsBoolean) { throw new SerializationException(); }  AimAtPlayer = _buf["aimAtPlayer"]; }
        { if(!_buf["burstCount"].IsNumber) { throw new SerializationException(); }  BurstCount = _buf["burstCount"]; }
        { if(!_buf["fireInterval"].IsNumber) { throw new SerializationException(); }  FireInterval = _buf["fireInterval"]; }
    }

    public static BulletPattern DeserializeBulletPattern(JSONNode _buf)
    {
        return new leiting.BulletPattern(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 子弹发射模式ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// Single/Fan/Aim/Ring等
    /// </summary>
    public readonly string PatternType;
    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly string BulletId;
    /// <summary>
    /// 挂点组
    /// </summary>
    public readonly string FirePointGroup;
    /// <summary>
    /// 挂点X偏移
    /// </summary>
    public readonly float FirePointOffsetX;
    /// <summary>
    /// 挂点Y偏移
    /// </summary>
    public readonly float FirePointOffsetY;
    /// <summary>
    /// 基础角度
    /// </summary>
    public readonly float BaseAngle;
    /// <summary>
    /// 每轮数量
    /// </summary>
    public readonly int BulletCount;
    /// <summary>
    /// 角度步进
    /// </summary>
    public readonly float AngleStep;
    /// <summary>
    /// 散布角
    /// </summary>
    public readonly float SpreadAngle;
    /// <summary>
    /// 覆盖子弹速度
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// 覆盖生命周期
    /// </summary>
    public readonly float BulletLifetime;
    /// <summary>
    /// 是否旋转
    /// </summary>
    public readonly bool Rotate;
    /// <summary>
    /// 旋转步进
    /// </summary>
    public readonly float RotationSpeed;
    /// <summary>
    /// 是否瞄准玩家
    /// </summary>
    public readonly bool AimAtPlayer;
    /// <summary>
    /// 连发轮数
    /// </summary>
    public readonly int BurstCount;
    /// <summary>
    /// 连发间隔
    /// </summary>
    public readonly float FireInterval;
   
    public const int __ID__ = -2040390882;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "patternType:" + PatternType + ","
        + "bulletId:" + BulletId + ","
        + "firePointGroup:" + FirePointGroup + ","
        + "firePointOffsetX:" + FirePointOffsetX + ","
        + "firePointOffsetY:" + FirePointOffsetY + ","
        + "baseAngle:" + BaseAngle + ","
        + "bulletCount:" + BulletCount + ","
        + "angleStep:" + AngleStep + ","
        + "spreadAngle:" + SpreadAngle + ","
        + "bulletSpeed:" + BulletSpeed + ","
        + "bulletLifetime:" + BulletLifetime + ","
        + "rotate:" + Rotate + ","
        + "rotationSpeed:" + RotationSpeed + ","
        + "aimAtPlayer:" + AimAtPlayer + ","
        + "burstCount:" + BurstCount + ","
        + "fireInterval:" + FireInterval + ","
        + "}";
    }
}
}

