
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class Bullet : Luban.BeanBase
{
    public Bullet(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["owner"].IsString) { throw new SerializationException(); }  Owner = _buf["owner"]; }
        { if(!_buf["firePattern"].IsString) { throw new SerializationException(); }  FirePattern = _buf["firePattern"]; }
        { if(!_buf["spritePath"].IsString) { throw new SerializationException(); }  SpritePath = _buf["spritePath"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["lifetime"].IsNumber) { throw new SerializationException(); }  Lifetime = _buf["lifetime"]; }
        { if(!_buf["sizeX"].IsNumber) { throw new SerializationException(); }  SizeX = _buf["sizeX"]; }
        { if(!_buf["sizeY"].IsNumber) { throw new SerializationException(); }  SizeY = _buf["sizeY"]; }
        { if(!_buf["glowColorR"].IsNumber) { throw new SerializationException(); }  GlowColorR = _buf["glowColorR"]; }
        { if(!_buf["glowColorG"].IsNumber) { throw new SerializationException(); }  GlowColorG = _buf["glowColorG"]; }
        { if(!_buf["glowColorB"].IsNumber) { throw new SerializationException(); }  GlowColorB = _buf["glowColorB"]; }
        { if(!_buf["glowColorA"].IsNumber) { throw new SerializationException(); }  GlowColorA = _buf["glowColorA"]; }
        { if(!_buf["glowRange"].IsNumber) { throw new SerializationException(); }  GlowRange = _buf["glowRange"]; }
        { if(!_buf["projectileCount"].IsNumber) { throw new SerializationException(); }  ProjectileCount = _buf["projectileCount"]; }
        { if(!_buf["spreadAngle"].IsNumber) { throw new SerializationException(); }  SpreadAngle = _buf["spreadAngle"]; }
        { if(!_buf["muzzleSpacing"].IsNumber) { throw new SerializationException(); }  MuzzleSpacing = _buf["muzzleSpacing"]; }
        { if(!_buf["pierceCount"].IsNumber) { throw new SerializationException(); }  PierceCount = _buf["pierceCount"]; }
        { if(!_buf["laserLength"].IsNumber) { throw new SerializationException(); }  LaserLength = _buf["laserLength"]; }
    }

    public static Bullet DeserializeBullet(JSONNode _buf)
    {
        return new leiting.Bullet(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 归属Player/Enemy
    /// </summary>
    public readonly string Owner;
    /// <summary>
    /// 玩家开火方式或弹体类型
    /// </summary>
    public readonly string FirePattern;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string SpritePath;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 存活时间
    /// </summary>
    public readonly float Lifetime;
    /// <summary>
    /// 碰撞/视觉宽
    /// </summary>
    public readonly float SizeX;
    /// <summary>
    /// 碰撞/视觉高
    /// </summary>
    public readonly float SizeY;
    /// <summary>
    /// 光晕R
    /// </summary>
    public readonly float GlowColorR;
    /// <summary>
    /// 光晕G
    /// </summary>
    public readonly float GlowColorG;
    /// <summary>
    /// 光晕B
    /// </summary>
    public readonly float GlowColorB;
    /// <summary>
    /// 光晕A
    /// </summary>
    public readonly float GlowColorA;
    /// <summary>
    /// 光晕范围
    /// </summary>
    public readonly float GlowRange;
    /// <summary>
    /// 玩家一次发射数量
    /// </summary>
    public readonly int ProjectileCount;
    /// <summary>
    /// 散射角度
    /// </summary>
    public readonly float SpreadAngle;
    /// <summary>
    /// 炮口间距
    /// </summary>
    public readonly float MuzzleSpacing;
    /// <summary>
    /// 穿透次数
    /// </summary>
    public readonly int PierceCount;
    /// <summary>
    /// 激光长度
    /// </summary>
    public readonly float LaserLength;
   
    public const int __ID__ = -1367175150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "owner:" + Owner + ","
        + "firePattern:" + FirePattern + ","
        + "spritePath:" + SpritePath + ","
        + "damage:" + Damage + ","
        + "speed:" + Speed + ","
        + "lifetime:" + Lifetime + ","
        + "sizeX:" + SizeX + ","
        + "sizeY:" + SizeY + ","
        + "glowColorR:" + GlowColorR + ","
        + "glowColorG:" + GlowColorG + ","
        + "glowColorB:" + GlowColorB + ","
        + "glowColorA:" + GlowColorA + ","
        + "glowRange:" + GlowRange + ","
        + "projectileCount:" + ProjectileCount + ","
        + "spreadAngle:" + SpreadAngle + ","
        + "muzzleSpacing:" + MuzzleSpacing + ","
        + "pierceCount:" + PierceCount + ","
        + "laserLength:" + LaserLength + ","
        + "}";
    }
}
}

