
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class Enemy : Luban.BeanBase
{
    public Enemy(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["displayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["displayName"]; }
        { if(!_buf["prefabPath"].IsString) { throw new SerializationException(); }  PrefabPath = _buf["prefabPath"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["moveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["moveSpeed"]; }
        { if(!_buf["attackInterval"].IsNumber) { throw new SerializationException(); }  AttackInterval = _buf["attackInterval"]; }
        { if(!_buf["bulletId"].IsString) { throw new SerializationException(); }  BulletId = _buf["bulletId"]; }
        { if(!_buf["bulletPatternId"].IsString) { throw new SerializationException(); }  BulletPatternId = _buf["bulletPatternId"]; }
        { if(!_buf["hitScaleFeedback"].IsBoolean) { throw new SerializationException(); }  HitScaleFeedback = _buf["hitScaleFeedback"]; }
        { if(!_buf["score"].IsNumber) { throw new SerializationException(); }  Score = _buf["score"]; }
    }

    public static Enemy DeserializeEnemy(JSONNode _buf)
    {
        return new leiting.Enemy(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 敌机或Boss ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 生命
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// 兜底单发子弹ID
    /// </summary>
    public readonly string BulletId;
    /// <summary>
    /// 默认子弹或导弹发射模式ID
    /// </summary>
    public readonly string BulletPatternId;
    /// <summary>
    /// 受击缩放反馈
    /// </summary>
    public readonly bool HitScaleFeedback;
    /// <summary>
    /// 击杀得分
    /// </summary>
    public readonly int Score;
   
    public const int __ID__ = 2036662904;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "prefabPath:" + PrefabPath + ","
        + "hp:" + Hp + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "attackInterval:" + AttackInterval + ","
        + "bulletId:" + BulletId + ","
        + "bulletPatternId:" + BulletPatternId + ","
        + "hitScaleFeedback:" + HitScaleFeedback + ","
        + "score:" + Score + ","
        + "}";
    }
}
}

