
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class EnemyDrop : Luban.BeanBase
{
    public EnemyDrop(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["enemyId"].IsString) { throw new SerializationException(); }  EnemyId = _buf["enemyId"]; }
        { if(!_buf["sort"].IsNumber) { throw new SerializationException(); }  Sort = _buf["sort"]; }
        { if(!_buf["itemId"].IsString) { throw new SerializationException(); }  ItemId = _buf["itemId"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { if(!_buf["dropOnce"].IsBoolean) { throw new SerializationException(); }  DropOnce = _buf["dropOnce"]; }
    }

    public static EnemyDrop DeserializeEnemyDrop(JSONNode _buf)
    {
        return new leiting.EnemyDrop(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 掉落行ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属敌机ID
    /// </summary>
    public readonly string EnemyId;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int Sort;
    /// <summary>
    /// 掉落物ID
    /// </summary>
    public readonly string ItemId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 本关只掉一次
    /// </summary>
    public readonly bool DropOnce;
   
    public const int __ID__ = 1640999303;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "enemyId:" + EnemyId + ","
        + "sort:" + Sort + ","
        + "itemId:" + ItemId + ","
        + "count:" + Count + ","
        + "dropOnce:" + DropOnce + ","
        + "}";
    }
}
}

