
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["displayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["displayName"]; }
        { if(!_buf["backgroundSpritePath"].IsString) { throw new SerializationException(); }  BackgroundSpritePath = _buf["backgroundSpritePath"]; }
        { if(!_buf["backgroundScrollSpeed"].IsNumber) { throw new SerializationException(); }  BackgroundScrollSpeed = _buf["backgroundScrollSpeed"]; }
        { if(!_buf["bgmPath"].IsString) { throw new SerializationException(); }  BgmPath = _buf["bgmPath"]; }
    }

    public static Level DeserializeLevel(JSONNode _buf)
    {
        return new leiting.Level(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 关卡显示名
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 背景图片路径
    /// </summary>
    public readonly string BackgroundSpritePath;
    /// <summary>
    /// 背景滚动速度
    /// </summary>
    public readonly float BackgroundScrollSpeed;
    /// <summary>
    /// 背景音乐路径
    /// </summary>
    public readonly string BgmPath;
   
    public const int __ID__ = 2042875508;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "backgroundSpritePath:" + BackgroundSpritePath + ","
        + "backgroundScrollSpeed:" + BackgroundScrollSpeed + ","
        + "bgmPath:" + BgmPath + ","
        + "}";
    }
}
}

