
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["displayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["displayName"]; }
        { if(!_buf["bossId"].IsString) { throw new SerializationException(); }  BossId = _buf["bossId"]; }
    }

    public static Level DeserializeLevel(JSONNode _buf)
    {
        return new leiting.Level(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 关卡显示名
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 本关Boss敌机ID
    /// </summary>
    public readonly string BossId;
   
    public const int __ID__ = 2042875508;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "bossId:" + BossId + ","
        + "}";
    }
}
}

