
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class Missile : Luban.BeanBase
{
    public Missile(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["missileId"].IsNumber) { throw new SerializationException(); }  MissileId = _buf["missileId"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["behaviorType"].IsNumber) { throw new SerializationException(); }  BehaviorType = _buf["behaviorType"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["maxSpeed"].IsNumber) { throw new SerializationException(); }  MaxSpeed = _buf["maxSpeed"]; }
        { if(!_buf["acceleration"].IsNumber) { throw new SerializationException(); }  Acceleration = _buf["acceleration"]; }
        { if(!_buf["lifeTime"].IsNumber) { throw new SerializationException(); }  LifeTime = _buf["lifeTime"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["radius"]; }
        { if(!_buf["turnSpeed"].IsNumber) { throw new SerializationException(); }  TurnSpeed = _buf["turnSpeed"]; }
        { if(!_buf["trackTime"].IsNumber) { throw new SerializationException(); }  TrackTime = _buf["trackTime"]; }
        { if(!_buf["lockDelay"].IsNumber) { throw new SerializationException(); }  LockDelay = _buf["lockDelay"]; }
        { if(!_buf["warningTime"].IsNumber) { throw new SerializationException(); }  WarningTime = _buf["warningTime"]; }
        { if(!_buf["explodeTime"].IsNumber) { throw new SerializationException(); }  ExplodeTime = _buf["explodeTime"]; }
        { if(!_buf["explodeRadius"].IsNumber) { throw new SerializationException(); }  ExplodeRadius = _buf["explodeRadius"]; }
        { if(!_buf["splitTime"].IsNumber) { throw new SerializationException(); }  SplitTime = _buf["splitTime"]; }
        { if(!_buf["splitCount"].IsNumber) { throw new SerializationException(); }  SplitCount = _buf["splitCount"]; }
        { if(!_buf["splitAngle"].IsNumber) { throw new SerializationException(); }  SplitAngle = _buf["splitAngle"]; }
        { if(!_buf["childMissileId"].IsString) { throw new SerializationException(); }  ChildMissileId = _buf["childMissileId"]; }
        { if(!_buf["canBeDestroyed"].IsBoolean) { throw new SerializationException(); }  CanBeDestroyed = _buf["canBeDestroyed"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["isLoopTrack"].IsBoolean) { throw new SerializationException(); }  IsLoopTrack = _buf["isLoopTrack"]; }
        { if(!_buf["prefabPath"].IsString) { throw new SerializationException(); }  PrefabPath = _buf["prefabPath"]; }
        { if(!_buf["bodyRes"].IsString) { throw new SerializationException(); }  BodyRes = _buf["bodyRes"]; }
        { if(!_buf["flyAnim"].IsString) { throw new SerializationException(); }  FlyAnim = _buf["flyAnim"]; }
        { if(!_buf["tailType"].IsString) { throw new SerializationException(); }  TailType = _buf["tailType"]; }
        { if(!_buf["tailRes"].IsString) { throw new SerializationException(); }  TailRes = _buf["tailRes"]; }
        { if(!_buf["tailColor"].IsString) { throw new SerializationException(); }  TailColor = _buf["tailColor"]; }
        { if(!_buf["warningRes"].IsString) { throw new SerializationException(); }  WarningRes = _buf["warningRes"]; }
        { if(!_buf["lockEffectRes"].IsString) { throw new SerializationException(); }  LockEffectRes = _buf["lockEffectRes"]; }
        { if(!_buf["explodeEffectRes"].IsString) { throw new SerializationException(); }  ExplodeEffectRes = _buf["explodeEffectRes"]; }
        { if(!_buf["hitEffectRes"].IsString) { throw new SerializationException(); }  HitEffectRes = _buf["hitEffectRes"]; }
        { if(!_buf["destroyEffectRes"].IsString) { throw new SerializationException(); }  DestroyEffectRes = _buf["destroyEffectRes"]; }
        { if(!_buf["effectRes"].IsString) { throw new SerializationException(); }  EffectRes = _buf["effectRes"]; }
        { if(!_buf["soundRes"].IsString) { throw new SerializationException(); }  SoundRes = _buf["soundRes"]; }
        { if(!_buf["soundLaunch"].IsString) { throw new SerializationException(); }  SoundLaunch = _buf["soundLaunch"]; }
        { if(!_buf["soundLock"].IsString) { throw new SerializationException(); }  SoundLock = _buf["soundLock"]; }
        { if(!_buf["soundExplode"].IsString) { throw new SerializationException(); }  SoundExplode = _buf["soundExplode"]; }
        { if(!_buf["waveAmplitude"].IsNumber) { throw new SerializationException(); }  WaveAmplitude = _buf["waveAmplitude"]; }
        { if(!_buf["waveFrequency"].IsNumber) { throw new SerializationException(); }  WaveFrequency = _buf["waveFrequency"]; }
        { if(!_buf["releaseInterval"].IsNumber) { throw new SerializationException(); }  ReleaseInterval = _buf["releaseInterval"]; }
        { if(!_buf["triggerRadius"].IsNumber) { throw new SerializationException(); }  TriggerRadius = _buf["triggerRadius"]; }
        { if(!_buf["returnDelay"].IsNumber) { throw new SerializationException(); }  ReturnDelay = _buf["returnDelay"]; }
    }

    public static Missile DeserializeMissile(JSONNode _buf)
    {
        return new leiting.Missile(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 导弹ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 数值ID
    /// </summary>
    public readonly int MissileId;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 行为类型
    /// </summary>
    public readonly int BehaviorType;
    /// <summary>
    /// 初速
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 最大速度
    /// </summary>
    public readonly float MaxSpeed;
    /// <summary>
    /// 加速度
    /// </summary>
    public readonly float Acceleration;
    /// <summary>
    /// 存活时间
    /// </summary>
    public readonly float LifeTime;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 转向速度
    /// </summary>
    public readonly float TurnSpeed;
    /// <summary>
    /// 追踪时长
    /// </summary>
    public readonly float TrackTime;
    /// <summary>
    /// 锁定延迟
    /// </summary>
    public readonly float LockDelay;
    /// <summary>
    /// 预警时间
    /// </summary>
    public readonly float WarningTime;
    /// <summary>
    /// 爆炸时间
    /// </summary>
    public readonly float ExplodeTime;
    /// <summary>
    /// 爆炸半径
    /// </summary>
    public readonly float ExplodeRadius;
    /// <summary>
    /// 分裂时间
    /// </summary>
    public readonly float SplitTime;
    /// <summary>
    /// 分裂数量
    /// </summary>
    public readonly int SplitCount;
    /// <summary>
    /// 分裂角度
    /// </summary>
    public readonly float SplitAngle;
    /// <summary>
    /// 子导弹ID
    /// </summary>
    public readonly string ChildMissileId;
    /// <summary>
    /// 可被摧毁
    /// </summary>
    public readonly bool CanBeDestroyed;
    /// <summary>
    /// 导弹生命
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 循环追踪
    /// </summary>
    public readonly bool IsLoopTrack;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 主体资源
    /// </summary>
    public readonly string BodyRes;
    /// <summary>
    /// 飞行动画
    /// </summary>
    public readonly string FlyAnim;
    /// <summary>
    /// 尾焰类型
    /// </summary>
    public readonly string TailType;
    /// <summary>
    /// 尾焰资源
    /// </summary>
    public readonly string TailRes;
    /// <summary>
    /// 尾焰颜色
    /// </summary>
    public readonly string TailColor;
    /// <summary>
    /// 预警资源
    /// </summary>
    public readonly string WarningRes;
    /// <summary>
    /// 锁定特效
    /// </summary>
    public readonly string LockEffectRes;
    /// <summary>
    /// 爆炸特效
    /// </summary>
    public readonly string ExplodeEffectRes;
    /// <summary>
    /// 命中特效
    /// </summary>
    public readonly string HitEffectRes;
    /// <summary>
    /// 摧毁特效
    /// </summary>
    public readonly string DestroyEffectRes;
    /// <summary>
    /// 通用特效
    /// </summary>
    public readonly string EffectRes;
    /// <summary>
    /// 通用音效
    /// </summary>
    public readonly string SoundRes;
    /// <summary>
    /// 发射音效
    /// </summary>
    public readonly string SoundLaunch;
    /// <summary>
    /// 锁定音效
    /// </summary>
    public readonly string SoundLock;
    /// <summary>
    /// 爆炸音效
    /// </summary>
    public readonly string SoundExplode;
    /// <summary>
    /// 波形幅度
    /// </summary>
    public readonly float WaveAmplitude;
    /// <summary>
    /// 波形频率
    /// </summary>
    public readonly float WaveFrequency;
    /// <summary>
    /// 释放间隔
    /// </summary>
    public readonly float ReleaseInterval;
    /// <summary>
    /// 触发半径
    /// </summary>
    public readonly float TriggerRadius;
    /// <summary>
    /// 返回延迟
    /// </summary>
    public readonly float ReturnDelay;
   
    public const int __ID__ = 1402976278;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "missileId:" + MissileId + ","
        + "name:" + Name + ","
        + "behaviorType:" + BehaviorType + ","
        + "speed:" + Speed + ","
        + "maxSpeed:" + MaxSpeed + ","
        + "acceleration:" + Acceleration + ","
        + "lifeTime:" + LifeTime + ","
        + "damage:" + Damage + ","
        + "radius:" + Radius + ","
        + "turnSpeed:" + TurnSpeed + ","
        + "trackTime:" + TrackTime + ","
        + "lockDelay:" + LockDelay + ","
        + "warningTime:" + WarningTime + ","
        + "explodeTime:" + ExplodeTime + ","
        + "explodeRadius:" + ExplodeRadius + ","
        + "splitTime:" + SplitTime + ","
        + "splitCount:" + SplitCount + ","
        + "splitAngle:" + SplitAngle + ","
        + "childMissileId:" + ChildMissileId + ","
        + "canBeDestroyed:" + CanBeDestroyed + ","
        + "hp:" + Hp + ","
        + "isLoopTrack:" + IsLoopTrack + ","
        + "prefabPath:" + PrefabPath + ","
        + "bodyRes:" + BodyRes + ","
        + "flyAnim:" + FlyAnim + ","
        + "tailType:" + TailType + ","
        + "tailRes:" + TailRes + ","
        + "tailColor:" + TailColor + ","
        + "warningRes:" + WarningRes + ","
        + "lockEffectRes:" + LockEffectRes + ","
        + "explodeEffectRes:" + ExplodeEffectRes + ","
        + "hitEffectRes:" + HitEffectRes + ","
        + "destroyEffectRes:" + DestroyEffectRes + ","
        + "effectRes:" + EffectRes + ","
        + "soundRes:" + SoundRes + ","
        + "soundLaunch:" + SoundLaunch + ","
        + "soundLock:" + SoundLock + ","
        + "soundExplode:" + SoundExplode + ","
        + "waveAmplitude:" + WaveAmplitude + ","
        + "waveFrequency:" + WaveFrequency + ","
        + "releaseInterval:" + ReleaseInterval + ","
        + "triggerRadius:" + TriggerRadius + ","
        + "returnDelay:" + ReturnDelay + ","
        + "}";
    }
}
}

