
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class PickupItem : Luban.BeanBase
{
    public PickupItem(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["displayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["displayName"]; }
        { if(!_buf["itemType"].IsString) { throw new SerializationException(); }  ItemType = _buf["itemType"]; }
        { if(!_buf["spritePath"].IsString) { throw new SerializationException(); }  SpritePath = _buf["spritePath"]; }
        { if(!_buf["starValue"].IsNumber) { throw new SerializationException(); }  StarValue = _buf["starValue"]; }
        { if(!_buf["coinValue"].IsNumber) { throw new SerializationException(); }  CoinValue = _buf["coinValue"]; }
        { if(!_buf["healValue"].IsNumber) { throw new SerializationException(); }  HealValue = _buf["healValue"]; }
        { if(!_buf["shieldDuration"].IsNumber) { throw new SerializationException(); }  ShieldDuration = _buf["shieldDuration"]; }
        { if(!_buf["lifetime"].IsNumber) { throw new SerializationException(); }  Lifetime = _buf["lifetime"]; }
        { if(!_buf["driftSpeed"].IsNumber) { throw new SerializationException(); }  DriftSpeed = _buf["driftSpeed"]; }
        { if(!_buf["pickupRadius"].IsNumber) { throw new SerializationException(); }  PickupRadius = _buf["pickupRadius"]; }
        { if(!_buf["visualScale"].IsNumber) { throw new SerializationException(); }  VisualScale = _buf["visualScale"]; }
    }

    public static PickupItem DeserializePickupItem(JSONNode _buf)
    {
        return new leiting.PickupItem(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 掉落物ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly string ItemType;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string SpritePath;
    /// <summary>
    /// 星星值
    /// </summary>
    public readonly int StarValue;
    /// <summary>
    /// 金币值
    /// </summary>
    public readonly int CoinValue;
    /// <summary>
    /// 回血值
    /// </summary>
    public readonly int HealValue;
    /// <summary>
    /// 护盾持续时间
    /// </summary>
    public readonly float ShieldDuration;
    /// <summary>
    /// 存活时间
    /// </summary>
    public readonly float Lifetime;
    /// <summary>
    /// 下落速度
    /// </summary>
    public readonly float DriftSpeed;
    /// <summary>
    /// 拾取半径
    /// </summary>
    public readonly float PickupRadius;
    /// <summary>
    /// 视觉缩放
    /// </summary>
    public readonly float VisualScale;
   
    public const int __ID__ = 871268031;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "itemType:" + ItemType + ","
        + "spritePath:" + SpritePath + ","
        + "starValue:" + StarValue + ","
        + "coinValue:" + CoinValue + ","
        + "healValue:" + HealValue + ","
        + "shieldDuration:" + ShieldDuration + ","
        + "lifetime:" + Lifetime + ","
        + "driftSpeed:" + DriftSpeed + ","
        + "pickupRadius:" + PickupRadius + ","
        + "visualScale:" + VisualScale + ","
        + "}";
    }
}
}

