
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class Player : Luban.BeanBase
{
    public Player(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["displayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["displayName"]; }
        { if(!_buf["prefabPath"].IsString) { throw new SerializationException(); }  PrefabPath = _buf["prefabPath"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["shield"].IsNumber) { throw new SerializationException(); }  Shield = _buf["shield"]; }
        { if(!_buf["stars"].IsNumber) { throw new SerializationException(); }  Stars = _buf["stars"]; }
        { if(!_buf["coins"].IsNumber) { throw new SerializationException(); }  Coins = _buf["coins"]; }
        { if(!_buf["moveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["moveSpeed"]; }
        { if(!_buf["invincibleTime"].IsNumber) { throw new SerializationException(); }  InvincibleTime = _buf["invincibleTime"]; }
        { if(!_buf["pickupAttractRange"].IsNumber) { throw new SerializationException(); }  PickupAttractRange = _buf["pickupAttractRange"]; }
        { if(!_buf["pickupAttractSpeed"].IsNumber) { throw new SerializationException(); }  PickupAttractSpeed = _buf["pickupAttractSpeed"]; }
        { if(!_buf["visualScale"].IsNumber) { throw new SerializationException(); }  VisualScale = _buf["visualScale"]; }
        { if(!_buf["hitboxRadius"].IsNumber) { throw new SerializationException(); }  HitboxRadius = _buf["hitboxRadius"]; }
        { if(!_buf["hitboxOffsetX"].IsNumber) { throw new SerializationException(); }  HitboxOffsetX = _buf["hitboxOffsetX"]; }
        { if(!_buf["hitboxOffsetY"].IsNumber) { throw new SerializationException(); }  HitboxOffsetY = _buf["hitboxOffsetY"]; }
        { if(!_buf["defaultBulletId"].IsString) { throw new SerializationException(); }  DefaultBulletId = _buf["defaultBulletId"]; }
        { if(!_buf["fireInterval"].IsNumber) { throw new SerializationException(); }  FireInterval = _buf["fireInterval"]; }
        { if(!_buf["fireSoundPath"].IsString) { throw new SerializationException(); }  FireSoundPath = _buf["fireSoundPath"]; }
    }

    public static Player DeserializePlayer(JSONNode _buf)
    {
        return new leiting.Player(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 玩家飞机ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 显示名
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 玩家预制体路径
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 初始生命
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 初始护盾
    /// </summary>
    public readonly int Shield;
    /// <summary>
    /// 初始星星
    /// </summary>
    public readonly int Stars;
    /// <summary>
    /// 初始金币
    /// </summary>
    public readonly int Coins;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 受击无敌时间
    /// </summary>
    public readonly float InvincibleTime;
    /// <summary>
    /// 吸附范围
    /// </summary>
    public readonly float PickupAttractRange;
    /// <summary>
    /// 吸附速度
    /// </summary>
    public readonly float PickupAttractSpeed;
    /// <summary>
    /// 视觉缩放
    /// </summary>
    public readonly float VisualScale;
    /// <summary>
    /// 受击判定半径
    /// </summary>
    public readonly float HitboxRadius;
    /// <summary>
    /// 受击判定X偏移
    /// </summary>
    public readonly float HitboxOffsetX;
    /// <summary>
    /// 受击判定Y偏移
    /// </summary>
    public readonly float HitboxOffsetY;
    /// <summary>
    /// 默认子弹ID
    /// </summary>
    public readonly string DefaultBulletId;
    /// <summary>
    /// 开火间隔
    /// </summary>
    public readonly float FireInterval;
    /// <summary>
    /// 开火音效路径
    /// </summary>
    public readonly string FireSoundPath;
   
    public const int __ID__ = -974993935;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "prefabPath:" + PrefabPath + ","
        + "hp:" + Hp + ","
        + "shield:" + Shield + ","
        + "stars:" + Stars + ","
        + "coins:" + Coins + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "invincibleTime:" + InvincibleTime + ","
        + "pickupAttractRange:" + PickupAttractRange + ","
        + "pickupAttractSpeed:" + PickupAttractSpeed + ","
        + "visualScale:" + VisualScale + ","
        + "hitboxRadius:" + HitboxRadius + ","
        + "hitboxOffsetX:" + HitboxOffsetX + ","
        + "hitboxOffsetY:" + HitboxOffsetY + ","
        + "defaultBulletId:" + DefaultBulletId + ","
        + "fireInterval:" + FireInterval + ","
        + "fireSoundPath:" + FireSoundPath + ","
        + "}";
    }
}
}

