
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class StageEvent : Luban.BeanBase
{
    public StageEvent(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["levelId"].IsString) { throw new SerializationException(); }  LevelId = _buf["levelId"]; }
        { if(!_buf["startTime"].IsNumber) { throw new SerializationException(); }  StartTime = _buf["startTime"]; }
        { if(!_buf["message"].IsString) { throw new SerializationException(); }  Message = _buf["message"]; }
        { if(!_buf["clearEnemyBullets"].IsBoolean) { throw new SerializationException(); }  ClearEnemyBullets = _buf["clearEnemyBullets"]; }
    }

    public static StageEvent DeserializeStageEvent(JSONNode _buf)
    {
        return new leiting.StageEvent(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 事件ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属关卡ID；空=所有关卡
    /// </summary>
    public readonly string LevelId;
    /// <summary>
    /// 触发秒数
    /// </summary>
    public readonly float StartTime;
    /// <summary>
    /// 提示文案
    /// </summary>
    public readonly string Message;
    /// <summary>
    /// 是否清弹/导弹
    /// </summary>
    public readonly bool ClearEnemyBullets;
   
    public const int __ID__ = -1362554548;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "startTime:" + StartTime + ","
        + "message:" + Message + ","
        + "clearEnemyBullets:" + ClearEnemyBullets + ","
        + "}";
    }
}
}

