
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
/// <summary>
/// 敌机掉落配置
/// </summary>
public partial class TbEnemyDrop
{
    private readonly System.Collections.Generic.List<leiting.EnemyDrop> _dataList;


    public TbEnemyDrop(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<leiting.EnemyDrop>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            leiting.EnemyDrop _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.leiting.EnemyDrop.DeserializeEnemyDrop(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<leiting.EnemyDrop> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

