
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
/// <summary>
/// 掉落物配置
/// </summary>
public partial class TbPickupItem
{
    private readonly System.Collections.Generic.List<leiting.PickupItem> _dataList;


    public TbPickupItem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<leiting.PickupItem>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            leiting.PickupItem _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.leiting.PickupItem.DeserializePickupItem(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<leiting.PickupItem> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

