
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
/// <summary>
/// 刷怪组配置
/// </summary>
public partial class TbWaveSpawn
{
    private readonly System.Collections.Generic.List<leiting.WaveSpawn> _dataList;


    public TbWaveSpawn(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<leiting.WaveSpawn>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            leiting.WaveSpawn _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.leiting.WaveSpawn.DeserializeWaveSpawn(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<leiting.WaveSpawn> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

