
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class Wave : Luban.BeanBase
{
    public Wave(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["levelId"].IsString) { throw new SerializationException(); }  LevelId = _buf["levelId"]; }
        { if(!_buf["startTime"].IsNumber) { throw new SerializationException(); }  StartTime = _buf["startTime"]; }
    }

    public static Wave DeserializeWave(JSONNode _buf)
    {
        return new leiting.Wave(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 波次ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属关卡ID；空=所有关卡
    /// </summary>
    public readonly string LevelId;
    /// <summary>
    /// 关卡开始后触发秒数
    /// </summary>
    public readonly float StartTime;
   
    public const int __ID__ = 1728791049;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "startTime:" + StartTime + ","
        + "}";
    }
}
}

