
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.leiting
{
public sealed partial class WaveSpawn : Luban.BeanBase
{
    public WaveSpawn(JSONNode _buf) 
    {
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["waveId"].IsString) { throw new SerializationException(); }  WaveId = _buf["waveId"]; }
        { if(!_buf["sort"].IsNumber) { throw new SerializationException(); }  Sort = _buf["sort"]; }
        { if(!_buf["enemyId"].IsString) { throw new SerializationException(); }  EnemyId = _buf["enemyId"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { if(!_buf["interval"].IsNumber) { throw new SerializationException(); }  Interval = _buf["interval"]; }
        { if(!_buf["startPositionX"].IsNumber) { throw new SerializationException(); }  StartPositionX = _buf["startPositionX"]; }
        { if(!_buf["startPositionY"].IsNumber) { throw new SerializationException(); }  StartPositionY = _buf["startPositionY"]; }
        { if(!_buf["attackPatternId"].IsString) { throw new SerializationException(); }  AttackPatternId = _buf["attackPatternId"]; }
        { if(!_buf["movementPath"].IsString) { throw new SerializationException(); }  MovementPath = _buf["movementPath"]; }
        { if(!_buf["pathAmplitude"].IsNumber) { throw new SerializationException(); }  PathAmplitude = _buf["pathAmplitude"]; }
        { if(!_buf["pathSpeed"].IsNumber) { throw new SerializationException(); }  PathSpeed = _buf["pathSpeed"]; }
        { if(!_buf["holdDuration"].IsNumber) { throw new SerializationException(); }  HoldDuration = _buf["holdDuration"]; }
    }

    public static WaveSpawn DeserializeWaveSpawn(JSONNode _buf)
    {
        return new leiting.WaveSpawn(_buf);
    }

    public readonly int Index;
    /// <summary>
    /// 刷怪行ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属波次ID
    /// </summary>
    public readonly string WaveId;
    /// <summary>
    /// 执行顺序
    /// </summary>
    public readonly int Sort;
    /// <summary>
    /// 敌机ID
    /// </summary>
    public readonly string EnemyId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 生成间隔
    /// </summary>
    public readonly float Interval;
    /// <summary>
    /// 出生X
    /// </summary>
    public readonly float StartPositionX;
    /// <summary>
    /// 出生Y
    /// </summary>
    public readonly float StartPositionY;
    /// <summary>
    /// 覆盖攻击模式ID
    /// </summary>
    public readonly string AttackPatternId;
    /// <summary>
    /// 移动路径
    /// </summary>
    public readonly string MovementPath;
    /// <summary>
    /// 路径幅度
    /// </summary>
    public readonly float PathAmplitude;
    /// <summary>
    /// 路径速度
    /// </summary>
    public readonly float PathSpeed;
    /// <summary>
    /// 停留时间
    /// </summary>
    public readonly float HoldDuration;
   
    public const int __ID__ = -70279438;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "index:" + Index + ","
        + "id:" + Id + ","
        + "waveId:" + WaveId + ","
        + "sort:" + Sort + ","
        + "enemyId:" + EnemyId + ","
        + "count:" + Count + ","
        + "interval:" + Interval + ","
        + "startPositionX:" + StartPositionX + ","
        + "startPositionY:" + StartPositionY + ","
        + "attackPatternId:" + AttackPatternId + ","
        + "movementPath:" + MovementPath + ","
        + "pathAmplitude:" + PathAmplitude + ","
        + "pathSpeed:" + PathSpeed + ","
        + "holdDuration:" + HoldDuration + ","
        + "}";
    }
}
}

