
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 玩家飞机配置
    /// </summary>
    public leiting.TbPlayer TbPlayer {get; }
    /// <summary>
    /// Boss阶段配置
    /// </summary>
    public leiting.TbBossPhase TbBossPhase {get; }
    /// <summary>
    /// Boss阶段弹幕关系
    /// </summary>
    public leiting.TbBossPhasePattern TbBossPhasePattern {get; }
    /// <summary>
    /// Boss技能配置
    /// </summary>
    public leiting.TbBossSkill TbBossSkill {get; }
    /// <summary>
    /// 子弹配置
    /// </summary>
    public leiting.TbBullet TbBullet {get; }
    /// <summary>
    /// 子弹发射模式
    /// </summary>
    public leiting.TbBulletPattern TbBulletPattern {get; }
    /// <summary>
    /// 敌机与Boss基础配置
    /// </summary>
    public leiting.TbEnemy TbEnemy {get; }
    /// <summary>
    /// 敌机掉落配置
    /// </summary>
    public leiting.TbEnemyDrop TbEnemyDrop {get; }
    /// <summary>
    /// 关卡配置
    /// </summary>
    public leiting.TbLevel TbLevel {get; }
    /// <summary>
    /// 导弹配置
    /// </summary>
    public leiting.TbMissile TbMissile {get; }
    /// <summary>
    /// 导弹发射模式
    /// </summary>
    public leiting.TbMissilePattern TbMissilePattern {get; }
    /// <summary>
    /// 掉落物配置
    /// </summary>
    public leiting.TbPickupItem TbPickupItem {get; }
    /// <summary>
    /// 关卡事件配置
    /// </summary>
    public leiting.TbStageEvent TbStageEvent {get; }
    /// <summary>
    /// 波次配置
    /// </summary>
    public leiting.TbWave TbWave {get; }
    /// <summary>
    /// 刷怪组配置
    /// </summary>
    public leiting.TbWaveSpawn TbWaveSpawn {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbPlayer = new leiting.TbPlayer(loader("leiting_tbplayer"));
        TbBossPhase = new leiting.TbBossPhase(loader("leiting_tbbossphase"));
        TbBossPhasePattern = new leiting.TbBossPhasePattern(loader("leiting_tbbossphasepattern"));
        TbBossSkill = new leiting.TbBossSkill(loader("leiting_tbbossskill"));
        TbBullet = new leiting.TbBullet(loader("leiting_tbbullet"));
        TbBulletPattern = new leiting.TbBulletPattern(loader("leiting_tbbulletpattern"));
        TbEnemy = new leiting.TbEnemy(loader("leiting_tbenemy"));
        TbEnemyDrop = new leiting.TbEnemyDrop(loader("leiting_tbenemydrop"));
        TbLevel = new leiting.TbLevel(loader("leiting_tblevel"));
        TbMissile = new leiting.TbMissile(loader("leiting_tbmissile"));
        TbMissilePattern = new leiting.TbMissilePattern(loader("leiting_tbmissilepattern"));
        TbPickupItem = new leiting.TbPickupItem(loader("leiting_tbpickupitem"));
        TbStageEvent = new leiting.TbStageEvent(loader("leiting_tbstageevent"));
        TbWave = new leiting.TbWave(loader("leiting_tbwave"));
        TbWaveSpawn = new leiting.TbWaveSpawn(loader("leiting_tbwavespawn"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbPlayer.ResolveRef(this);
        TbBossPhase.ResolveRef(this);
        TbBossPhasePattern.ResolveRef(this);
        TbBossSkill.ResolveRef(this);
        TbBullet.ResolveRef(this);
        TbBulletPattern.ResolveRef(this);
        TbEnemy.ResolveRef(this);
        TbEnemyDrop.ResolveRef(this);
        TbLevel.ResolveRef(this);
        TbMissile.ResolveRef(this);
        TbMissilePattern.ResolveRef(this);
        TbPickupItem.ResolveRef(this);
        TbStageEvent.ResolveRef(this);
        TbWave.ResolveRef(this);
        TbWaveSpawn.ResolveRef(this);
    }
}

}

